generatorName: rust
inputSpec: openapi.json

packageName: gitbundle-sdk
packageVersion: 3.3.5
gitUserId: gitbundle
gitRepoId: sdk-rust

library: reqwest
mockall: true

additionalProperties:
  authors: "RenovZ <cgsixv@gmail.com>"

# templateDir: template
# files:
#   api.mustache:
#     templateType: API
#   api_client_default.mustache:
#     templateType: API
#     destinationFilename: default.rs
