generatorName: go
inputSpec: openapi.json

packageName: gitbundlesdk
packageVersion: 3.3.5
gitUserId: gitbundle
gitRepoId: sdk-go

additionalProperties:
  enumClassPrefix: true
  useOneOfDiscriminatorLookup: true
  withGoCodegenComment: false
  # gitRepoBaseURL: https://github.com/gitbundle/sdk-go
  # gitRepoBranch: main
